### ISSUE TITLE
2022-02-01 update breaks tray icon color on KDE Plasma

### ISSUE THREAD

**Issue by cthu1hoo** [flathub/org.telegram.desktop#377]
When upgrading to:

```
    Commit: 9ea69598973dd074344967f7d98ebc27c291959404e1dfeba59cc6689ca73ae1
    Parent: 84950701bb81aba29836d5cf6420ddd5450b40edaa907d95a906ec430f00cf98
   Subject: Update patches (3c3985fd)
      Date: 2022-02-01 15:26:59 +0000
   History:
```

on KDE Plasma tray icon always shows as dark, even on Breeze Twilight plasma theme. Downgrading to:

```
    Commit: 84950701bb81aba29836d5cf6420ddd5450b40edaa907d95a906ec430f00cf98
   Subject: Update patches (8405ff08)
      Date: 2022-01-23 00:23:20 +0000
```

Makes icon display properly again, i.e. light on dark taskbar, and vice versa. Using Fedora Kinoite, latest.

Thanks.
